---
- name: creating new user for ubuntu and centos
  hosts: all
  become: yes
  gather_facts: yes 
  gather_subset: [min, virtual] 

  vars:
    username: 'student22'
    publickey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIfL+AuewtJDR00J/JdYbj9zHQRH/p7Yi3ZcZulMJYW/ student22@students-vm'

  tasks:
  - name: Autocheck os family RedHat/Debian
    include_vars: "{{ ansible_os_family }}.yml"

  - name: Create a new user
    user:
      name: "{{ username }}"
      password: "{{ 'password' | password_hash('sha512') }}"
      shell: "{{ default_shell }}"
      create_home: yes
      state: present

  - name: Creating .ssh dir
    file:
      path: "/home/{{ username }}/.ssh"
      state: directory
      mode: 0700
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: Add public key
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ public_key }}"
